
-- категории
CREATE TABLE IF NOT EXISTS "category" (
	"id" SERIAL NOT NULL,
	"name" CHARACTER VARYING(255) NULL DEFAULT NULL,
	"description" TEXT NULL DEFAULT NULL,
	PRIMARY KEY ("id")
);

-- товары
CREATE TABLE IF NOT EXISTS "goods" (
	"id" SERIAL NOT NULL,
	"name" CHARACTER VARYING(255) NULL DEFAULT NULL,
	"description" TEXT NULL DEFAULT NULL,
	"count" INTEGER NULL DEFAULT NULL,
	"price" REAL NULL DEFAULT NULL,
	"category_id" INTEGER NULL DEFAULT NULL REFERENCES category (id) ON DELETE CASCADE,
	PRIMARY KEY ("id")
);
